# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/lfp_bram/lfp_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lfp_bram || ORIG_REF_NAME==lfp_bram} -quiet] -quiet

# XDC: g:/NERCN_LFP/FPGA_final project/DBS_FPGA/Goertzel_FFT/Goertzel_FFT.gen/sources_1/ip/lfp_bram/lfp_bram_ooc.xdc
