# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/date_1_25.xdc

# IP: ip/lfp_bram/lfp_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lfp_bram || ORIG_REF_NAME==lfp_bram} -quiet] -quiet

# IP: ip/hanning_bram/hanning_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hanning_bram || ORIG_REF_NAME==hanning_bram} -quiet] -quiet

# XDC: g:/NERCN_LFP/FPGA_final project/DBS_FPGA/data_1_9_semi_final/data_1_9_semi_final.gen/sources_1/ip/lfp_bram/lfp_bram_ooc.xdc

# XDC: g:/NERCN_LFP/FPGA_final project/DBS_FPGA/data_1_9_semi_final/data_1_9_semi_final.gen/sources_1/ip/hanning_bram/hanning_bram_ooc.xdc
